version: '3.8'

services:

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./src:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
  web:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    depends_on:
      - php

  db:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=craft
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql/db:/var/lib/mysql
      - ./docker/mysql:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: 'db'
      PMA_USER: 'root'
      PMA_PASSWORD: 'root'
    ports:
    - 8081:80

  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
      - 1025:1025
volumes:
  mysql-data:
